default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 

development:
  <<: *default
  # database: webapp_development
  database: default_db_1

test:
  <<: *default
  # database: webapp_test
  database: default_db_1

production:
  <<: *default
  # database: webapp_production
  database: default_db_1
  username: webapp
  password: <%= ENV['WEBAPP_DATABASE_PASSWORD'] %>