image:
    name: docker/compose:1.24.1
    entrypoint: [""]

services:
    - docker:dind

cache:
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"      

stages:
    - build
    - deploy

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

before_script:
    - export IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - export WEB_IMAGE=$IMAGE:web
    - apk add --no-cache openssh-client bash
    - chmod +x ./setup_env.sh
    - bash ./setup_env.sh
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build:
    stage: build
    script:
        - docker pull $IMAGE:web || true
        - docker-compose -f docker-compose.ci.yml build
        - docker push $IMAGE:web

deploy:
    stage: deploy
    script:
        - mkdir -p ~/.ssh
        - echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - cat ~/.ssh/id_rsa
        - chmod 700 ~/.ssh/id_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_rsa
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - chmod +x ./deploy.sh
        - scp  -o StrictHostKeyChecking=no -r ./.env ./docker-compose.ci.yml root@$DIGITAL_OCEAN_IP_ADDRESS:/myapp
        - bash ./deploy.sh