version: '3.7'
services:
    web:
        build: 
            context: ./webapp
            dockerfile: Dockerfile
            cache_from:
            - "${WEB_IMAGE}"
        image: "${WEB_IMAGE}"
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            -  ./webapp:/myapp
        ports:
            - "3000:3000"
        env_file: .env
        depends_on:
            - db
    db:
        image: postgres:11.1
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: {}
    static_volume: {}